config/routes.rb
require 'sidekiq/web'

Neighborly::Application.routes.draw do
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  devise_for :users, path: '',
    path_names:  {
      sign_in:  :login,
      sign_out: :logout,
      sign_up:  :sign_up
    },
    controllers: {
      omniauth_callbacks: :omniauth_callbacks,
      sessions:           :sessions
    }


  devise_scope :user do
    post '/sign_up', to: 'devise/registrations#create', as: :sign_up
  end

  get '/thank_you' => "static#thank_you"

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Neighborly::Balanced::Creditcard::Engine => '/balanced/creditcard/', as: :neighborly_balanced_creditcard
  mount Neighborly::Balanced::Bankaccount::Engine => '/balanced/bankaccount/', as: :neighborly_balanced_bankaccount
  mount Neighborly::Balanced::Engine => '/balanced/', as: :neighborly_balanced

  # Non production routes
  if Rails.env.development?
    resources :emails, only: [ :index, :show ]
  end

  # Channels
  constraints subdomain: /^(?!www|secure|test|local|staging|neighborly|neighborly-staging)(\w+)/ do
    namespace :channels, path: '' do
      get '/', to: 'profiles#show', as: :profile
      resources :channels_subscribers, only: [:index, :create, :destroy]

      namespace :admin do

        get '/', to: 'dashboard#index', as: :dashboard

        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end

        resources :followers, only: [ :index ]

        resources :projects, only: [ :index, :update] do
          member do
            put 'launch'
            put 'reject'
            put 'push_to_draft'
            put 'approve'
          end
        end
      end

      resource :profile, only: [:show]
      resources :projects, only: [:new, :create] do
        collection do
          get 'video'
        end
      end
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  mount Neighborly::Admin::Engine => '/admin/', as: :neighborly_admin

  # Root path should be after channel constraints
  root to: 'projects#index'

  # Static Pages
  get '/sitemap',               to: 'static#sitemap',             as: :sitemap
  get '/how-it-works',          to: 'static#how_it_works',        as: :how_it_works
  get "/about",                 to: "static#about",               as: :about
  get "/faq",                   to: "static#faq",                 as: :faq
  get "/terms",                 to: "static#terms",               as: :terms
  get "/privacy",               to: "static#privacy",             as: :privacy
  get "/start",                 to: "projects#start",             as: :start

  # Only accessible on development
  if Rails.env.development?
    get "/base",                to: "static#base",              as: :base
  end

  get "/discover/(:filter)(/near/:near)(/category/:category)(/tags/:tags)(/search/:search)", to: "discover#index", as: :discover

  resources :tags, only: [:index]

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Temporary
  get '/projects/neuse-river-greenway-benches-draft', to: redirect('/projects/neuse-river-greenway-benches')

  resources :projects, except: [ :destroy ] do
    resources :faqs, controller: 'projects/faqs', only: [ :index, :create, :destroy ]
    resources :terms, controller: 'projects/terms', only: [ :index, :create, :destroy ]
    resources :updates, controller: 'projects/updates', only: [ :index, :create, :destroy ]

    collection do
      get 'video'
    end

    member do
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'comments'
      get 'reports'
      get 'budget'
      get 'success'
    end

    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end

    resources :contributions, controller: 'projects/contributions', except: :update do
      member do
        put 'credits_checkout'
      end
    end
  end

  scope :login, controller: :sessions do
    devise_scope :user do
      get   :set_new_user_email
      patch :confirm_new_user_email
    end
  end

  resources :users, path: 'neighbors' do
    resources :questions, controller: 'users/questions', only: [:new, :create]
    resources :projects, controller: 'users/projects', only: [ :index ]
    resources :contributions, controller: 'users/contributions', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :authorizations, controller: 'users/authorizations', only: [:destroy]
    resources :unsubscribes, only: [:create]
    member do
      get :settings
      get :credits
      get :payments
      get :edit
      put :update_email
      put :update_password
    end
  end

  namespace :companies do
    get :contact, to: 'contacts#new'
    resources :contacts, only: [:create]
  end

  resources :images, only: [:new, :create]

  namespace :markdown do
    resources :previewer, only: :create
  end

  # Redirect from old users url to the new
  get "/users/:id", to: redirect('neighbors/%{id}')

  get "/set_email" => "users#set_email", as: :set_email_users
  get "/:id", to: redirect('projects/%{id}')
end

app/models/concerns/project/custom_validators.rb
module Project::CustomValidators
  extend ActiveSupport::Concern

  included do
    validate :permalink_cant_be_route, allow_nil: true

    def self.permalink_on_routes?(permalink)
      permalink && self.get_routes.include?(permalink.downcase)
    end

    def permalink_cant_be_route
      errors.add(:permalink, I18n.t("activerecord.errors.models.project.attributes.permalink.invalid")) if Project.permalink_on_routes?(permalink)
    end
  end
end

app/models/concerns/project/organization_type.rb
module Project::OrganizationType
  extend ActiveSupport::Concern

  included do
    class << self
      def organization_type_array
        organization_types.collect { |type| [I18n.t("project.organization_type.#{type}"), type] }
      end

      def organization_types
        [:municipality, :neighborhood_organization, :cid_bid, :registered_nonprofit, :nonprofit_501c3, :public_private_partnership, :other, :not_sure]
      end
    end
  end
end

app/models/concerns/project/video_handler.rb
module Project::VideoHandler
  extend ActiveSupport::Concern

  included do
    mount_uploader :video_thumbnail, ProjectUploader, mount_on: :video_thumbnail

    delegate :display_video_embed_url, to: :decorator

    def video
      @video ||= VideoInfo.get(self.video_url) if self.video_url.present?
    end

    def download_video_thumbnail
      self.video_thumbnail = open(self.video.thumbnail_large)  if self.video_valid?
      self.save
    rescue OpenURI::HTTPError, TypeError => e
      Rails.logger.info "-----> #{e.inspect}"
    end

    def update_video_embed_url
      self.video_embed_url = self.video.embed_url if self.video_valid?
      self.save
    end

    def video_valid?
      self.video_url.present? && self.video
    end
  end
end

app/controllers/channels/admin/projects_controller.rb
module Channels::Admin
  class ProjectsController < BaseController
    has_scope :by_id, :pg_search, :user_name_contains, :order_by, :with_state
    has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true

    before_filter do
      @total_projects =  channel.projects.size
    end

    [:approve, :launch, :reject, :push_to_draft].each do |name|
      define_method name do
        @project    = channel.projects.find_by_permalink!(params[:id])
        @project.send("#{name.to_s}!")
        redirect_to :back
      end
    end

    protected
    def begin_of_association_chain
      channel
    end

    def collection
      @projects = apply_scopes(channel.projects.page(params[:page]))
    end
  end
end

app/controllers/channels/projects_controller.rb
class Channels::ProjectsController < ProjectsController
  belongs_to :channel, finder: :find_by_permalink!, param: :profile_id

  # Inheriting from the original Projects controller
  # With one addition: we include the project into the current channel
  before_filter only: [:create] { params[:project][:channels] = [@channel] }

  prepend_before_filter{ params[:profile_id] = request.subdomain }
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  after_filter :verify_authorized, except: :index
  inherit_resources
  actions :show, :new, :edit, :create, :credits_checkout
  skip_before_filter :verify_authenticity_token, only: [:moip]
  skip_before_filter :set_persistent_warning
  has_scope :available_to_count, type: :boolean
  has_scope :with_state
  has_scope :page, default: 1
  belongs_to :project, finder: :find_by_permalink!

  def index
    @project = parent
    if request.xhr? && params[:page] && params[:page].to_i > 1
      render collection
    end
  end

  def edit
    authorize resource
  end

  def show
    authorize resource
  end

  def new
    @contribution = Contribution.new(project: parent, user: current_user)
    authorize @contribution

    @create_url = create_url
    @rewards = [empty_reward] + @project.rewards.not_soon.remaining.order(:minimum_value)

    if params[:reward_id] && (selected_reward = @project.rewards.not_soon.find(params[:reward_id])) && !selected_reward.sold_out?
      @contribution.reward = selected_reward
      @contribution.value = "%0.0f" % selected_reward.minimum_value
    end
  end

  def create
    @contribution = Contribution.new(permitted_params[:contribution].
                                     merge(user: current_user,
                                           project: parent))

    @contribution.reward_id = nil if params[:contribution][:reward_id].to_i == 0
    authorize @contribution

    create! do |success, failure|
      success.html do
        session[:thank_you_contribution_id] = @contribution.id
        flash.delete(:notice)
        return redirect_to edit_project_contribution_path(project_id: @project, id: @contribution.id)
      end

      failure.html do
        return redirect_to new_project_contribution_path(@project), flash: { failure: t('controllers.projects.contributions.create.error') }
      end
    end
  end

  def credits_checkout
    authorize resource
    if current_user.credits < @contribution.value
      flash.alert = t('controllers.projects.contributions.credits_checkout.no_credits')
      return redirect_to new_project_contribution_path(@contribution.project)
    end

    unless @contribution.confirmed?
      @contribution.update_attributes({ payment_method: 'Credits' })
      @contribution.confirm!
    end

    flash.notice = t('controllers.projects.contributions.credits_checkout.success')
    redirect_to project_contribution_path(parent, resource)
  end

  protected
  def permitted_params
    params.permit(policy(@contribution || Contribution).permitted_attributes)
  end

  def collection
    @contributions ||= apply_scopes(end_of_association_chain).available_to_display.order("confirmed_at DESC").per(10)
  end

  def empty_reward
    Reward.new(minimum_value: 0, description: t('controllers.projects.contributions.new.no_reward'))
  end

  def create_url
    if ::Configuration[:secure_review_host]
      return project_contributions_url(@project, {host: ::Configuration[:secure_review_host], protocol: 'https'})
    else
      return project_contributions_path(@project)
    end
  end
end

app/controllers/projects/faqs_controller.rb
class Projects::FaqsController < ApplicationController
  after_filter :verify_authorized, except: :index
  inherit_resources
  defaults resource_class: ProjectFaq, collection_name: :project_faqs

  actions :index, :create, :destroy
  belongs_to :project, finder: :find_by_permalink!

  def index
    @project = parent
  end

  def create
    @project_faq = ProjectFaq.new(permitted_params[:project_faq].merge(project: parent))
    authorize @project_faq
    create! { project_faqs_path(parent) }
  end

  def destroy
    authorize resource
    destroy! { project_faqs_path(parent) }
  end

  private
  def permitted_params
    params.permit(policy(@project_faq || ProjectFaq).permitted_attributes)
  end

  def collection
    @faqs ||= end_of_association_chain.order('created_at desc')
  end
end

app/controllers/projects/terms_controller.rb
class Projects::TermsController < ApplicationController
  after_filter :verify_authorized, except: :index
  inherit_resources
  defaults resource_class: ProjectDocument, collection_name: :project_documents

  actions :create, :destroy
  belongs_to :project, finder: :find_by_permalink!

  def index
    @project = parent
    @documents = parent.project_documents
  end

  def create
    @project_document = ProjectDocument.new(permitted_params[:project_document].
                                            merge(project: parent))
    authorize @project_document
    create! { project_terms_path(parent) }
  end

  def destroy
    authorize resource
    destroy! { project_terms_path(parent) }
  end

  private
  def permitted_params
    params.permit(policy(@project_document || ProjectDocument).permitted_attributes)
  end
end

app/controllers/projects/updates_controller.rb
class Projects::UpdatesController < ApplicationController
  after_filter :verify_authorized, except: :index
  inherit_resources
  actions :destroy
  belongs_to :project, finder: :find_by_permalink!

  def index
    @project = parent
    if request.xhr? && params[:page] && params[:page].to_i > 1
      render collection
    end
  end

  def create
    @update = Update.new(permitted_params[:update].
                         merge(project: parent, user: current_user))
    authorize @update
    @update.save
    render @update
  end

  def destroy
    authorize resource
    destroy! do
      if request.xhr?
        return render nothing: true
      else
        project_updates_path(parent)
      end
    end
  end

  private
  def permitted_params
    params.permit(policy(@update || Update).permitted_attributes)
  end

  def collection
    @updates ||= end_of_association_chain.visible_to(current_user).order('created_at desc').page(params[:page]).per(3)
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  after_filter :verify_authorized, except: [:index, :video, :video_embed, :embed,
                                            :embed_panel, :comments, :budget,
                                            :reward_contact, :send_reward_email,
                                            :start]

  inherit_resources
  defaults finder: :find_by_permalink!
  actions :create, :edit, :update
  respond_to :html

  def new
    @project = Project.new(user: current_user)
    authorize @project
  end

  def index
    projects_vars = { featured:    :featured,
                      recommended: :recommends,
                      successful:  :successful,
                      ending_soon: :expiring,
                      coming_soon: :soon }

    projects_vars.each do |var_name, scope|
      instance_variable_set "@#{var_name}", ProjectsForHome.send(scope)
    end

    @channels = Channel.with_state('online').order('RANDOM()').limit(4)
    @press_assets = PressAsset.order('created_at DESC').limit(5)
  end

  def create
    @project = Project.new(permitted_params[:project].merge(user: current_user))
    authorize @project
    create! { success_project_path(@project) }
  end

  def success
    authorize resource
  end

  def edit
    authorize resource
    edit!
  end

  def update
    authorize resource
    update! { edit_project_path(@project) }
  end

  def show
    authorize resource
    set_facebook_url_admin(resource.user)
    render :about if request.xhr?
  end

  def comments
    @project = resource
  end

  def reports
    authorize resource
  end

  def budget
    @project = resource
  end

  def video
    project = Project.new(video_url: params[:url])
    render json: project.video.to_json
  rescue VideoInfo::UrlError
    render json: nil
  end

  %w(embed video_embed).each do |method_name|
    define_method method_name do
      @title = resource.name
      render layout: 'embed'
    end
  end

  def embed_panel
    @project = resource
    render layout: !request.xhr?
  end

  def start
    @projects = ProjectsForHome.successful[0..2]
  end

  protected
  def permitted_params
    params.permit(policy(@project || Project).permitted_attributes)
  end
end

app/controllers/users/projects_controller.rb
class Users::ProjectsController < ApplicationController
  inherit_resources
  actions :index
  belongs_to :user

  def collection
    @projects ||= end_of_association_chain
  end
end

app/views/projects/_project.html.slim
- columns_n = if defined? columns then columns else 'large-3 medium-4' end
.project-box[itemscope itemtype="http://schema.org/CreativeWork" class="#{'soon' if project.soon?} #{'large large-9 medium-8 columns' if defined?(large)} #{'large large-12 medium-12 columns' if defined?(contribution)} #{columns_n + ' columns' unless defined?(large) || defined?(contribution)} #{project.category.to_s.parameterize if project.category}"]
  meta[itemprop="dateCreated" content=project.created_at.to_date]
  - if project.soon?
    - project_link = 'javascript:void(0)'
  - else
    - project_link = project_path(project)

  = link_to project_link, target: ( defined?(embed_link) ? :blank : '' ) do
    - if project.expired?
      .status-image
        - if project.successful? && project.reached_goal?
          = image_tag "successful.#{I18n.locale}.png"
        - elsif project.successful? && !project.reached_goal?
          = image_tag "successful_flex.#{I18n.locale}.png"
        - elsif project.failed?
          = image_tag "not_successful.#{I18n.locale}.png"
    - elsif project.soon?
      .status-image
        = image_tag "coming_soon.#{I18n.locale}.png"

    .cover[class="#{'large-8 medium-8 columns' if defined?(large)} #{'large-6 columns' if defined?(contribution)} "]
      = image_tag project.display_image(defined?(large) || defined?(contribution) ? 'project_thumb_large' : 'project_thumb'), itemprop: 'image'

    .content[class="#{'large-4 medium-4 columns' if defined?(large)} #{'large-3 columns' if defined?(contribution)}"]
      - if defined?(large) || defined?(contribution)
        h4.name = project.name

      .category
        i[title=project.category.to_s]
        span = project.category.to_s

      - unless defined?(large) || defined?(contribution)
        h4.name = project.name

      .location
        i.icon-et-location
        | &nbsp;
        = project.location

      - if (defined?(large) || !browser.ie8? || defined?(contribution))
        .description[itemprop="description"]
          span = truncate(project.headline, length: 140, separator: ' ')
          a

      .status
        .row.collapse
          .pledged.large-6.columns = "#{project.display_pledged} (#{project.progress}%)"
          .time.project.large-6.columns
            i.icon-et-clock
            - if project.soon?
              = t('.soon')
            - elsif project.expired?
              = t('.completed')
            - else
              = "#{project.time_to_go[:time]} #{project.time_to_go[:unit]} #{project.remaining_text}"
        = project.progress_bar

    - if defined?(contribution)
      .back-informations.large-3.columns
        h5
          - contribution.confirmed_at.present?
            i.icon-et-calendar
            = l contribution.confirmed_at.to_date, format: :long

        - if contribution.display_value
          h5
            i.icon-et-heart
            = contribution.display_value
        - if contribution.reward
          .reward
            h5
              i.icon-et-trophy
              = t('rewards.index.reward_title', minimum: contribution.reward.display_minimum)
            - description = contribution.reward.description.gsub(/"/,'&quot;')
            p[title=description] = truncate(contribution.reward.description, length: 160)

        .share.row
          .large-6.columns
            = link_to t('.share.facebook'), "http://www.facebook.com/sharer.php?s=100&p[title]=#{project.name}&p[summary]=#{project.headline}&p[url]=#{project_url(project)}&p[images[0]=#{project.display_image('project_thumb_facebook')}", class: 'button with-icon facebook', target: :blank
          .large-6.columns
            = link_to t('.share.twitter'), "https://twitter.com/intent/tweet?text=#{URI::encode(t('.share.twitter-text', name: project.name, hash_tag: project.hash_tag))}", class: 'button with-icon twitter', target: :blank

app/views/projects/_rejected_warning.html.slim
.row
  section.panel.callout.radius
    p This project was not selected to participate on Neighbor.ly. Maybe next time! :)

app/views/projects/budget.html.slim
- content_for :page_content do
  .user-content = @project.budget_html

- if request.xhr?
  = yield :page_content
- else
  = render template: 'projects/show'

app/views/projects/embed_panel.html.slim
a.close-reveal-modal ×
br/
- if @project.foundation_widget?
  - box_width = '225px'
  - box_height = '543px'
- else
  - box_width = '250px'
  - box_height = '335px'
- video_width = '390px'
- video_height = '335px'


.embed-panel-page
  .row.collapse.header
    .large-12.column
      h3 = t('.title')
      p = t('.subtitle')
  .row.collapse.content
    .large-5.small-12.medium-12.columns
      h5 = t('.campaign_progress')
      iframe frameborder='0' height=box_height width=box_width src=embed_project_path(@project)
      form.html= text_area_tag 'project-box-embed-html', '<iframe frameborder="0" height="' + box_height + '" src="' + embed_project_url(@project) + '" width="' + box_width + '"></iframe>', readonly: true

    .large-7.small-12.medium-12.column.video-embed-wrapper
      h5 = t('.campaign_video')
      iframe frameborder='0' height=video_height width=video_width src=video_embed_project_path(@project)
      form.html= text_area_tag 'project-video-embed-html', '<iframe frameborder="0" height="' + video_height + '" src="' + video_embed_project_url(@project) + '" width="' + video_width + '"></iframe>', readonly: true

app/views/projects/show.html.slim
- content_for :title, @project.name
= render partial: 'layouts/disqus_count'
= content_for :meta_tags do
  - if @update
    meta name="description" content=@update.title
    meta property="og:title" content=@update.title
    meta property="og:description" content=@update.comment
    meta property="og:url" content=project_url(@project, update_id: @update.id)
  - else
    meta name="description" content=@project.headline
    meta property="og:title" content=@project.name
    meta property="og:description" content=@project.headline
    meta property="og:url" content=project_url(@project)
  meta property="og:type" content='cause'
  meta property="og:image" content=@project.display_image('project_thumb_facebook')
  meta property="og:site_name" content=::Configuration[:company_name]
  meta property="fb:admins" content=facebook_url_admin

.project-page
  = hero_header_tag @project do
    .row
      .large-12.columns
        .name
          h3 = @project.name
      .large-8.columns
        iframe src="#{@project.display_video_embed_url}" width="636 " height="358" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen
        .row
          .large-6.small-8.columns.share-small
            = render 'projects/share'
          .large-6.small-4.columns.time-remaining
            i.icon-et-clock
            - if @project.draft? || @project.rejected?
              strong = @project.online_days
              = " #{pluralize_without_number(@project.online_days, I18n.t('datetime.prompts.day').downcase)} #{pluralize_without_number(@project.online_days, t('words.remaining_singular'), t('words.remaining_plural'))}"
            - else
              strong = @project.remaining_days
              = " #{@project.time_to_go[:unit].capitalize} #{pluralize_without_number(@project.time_to_go[:time], t('words.remaining_singular'), t('words.remaining_plural'))}"


      .large-4.columns
        .subtitle
          h5= t(".subtitle.#{@project.campaign_type}", category_name: link_to(@project.category, discover_path(category: @project.category.to_s.downcase)), city: @project.display_address_formated, author: link_to(@project.user.display_name, user_path(@project.user))).html_safe
        hr
        .headline
          p = @project.headline
        .status
          = @project.progress_bar
          .pledged
            = @project.display_pledged
            small = t('.so_far').html_safe
            = @project.display_goal

  section.status-bar.fixed
    .row
      .large-12.columns.status
        .row
          .large-3.columns.share-small
            = render 'projects/share', embed: false
          .large-2.columns.pledged
            p = "#{@project.display_pledged} (#{@project.progress}%)"
          .large-2.columns.contributions
            p
              i.icon-et-user
              = t('.status-bar.total_contributions', value: @project.total_contributions)
          .large-2.columns.time-remaining
            p
              i.icon-et-clock
              - if @project.draft? || @project.rejected?
                = "#{@project.online_days} #{pluralize_without_number(@project.online_days, I18n.t('datetime.prompts.day').downcase)} #{pluralize_without_number(@project.online_days, t('words.remaining_singular'), t('words.remaining_plural'))}"
              - else
                = "#{@project.remaining_days} #{@project.time_to_go[:unit].capitalize} #{pluralize_without_number(@project.time_to_go[:time], t('words.remaining_singular'), t('words.remaining_plural'))}"

          - unless @project.online?
            .large-3.columns.status-description
              span = t(".display_status.#{@project.campaign_type}.#{@project.display_status}", goal: @project.display_goal, date: (l(@project.display_expires_at.to_date, format: :long) rescue nil))
          - else
            .large-3.columns.contribute
              = link_to t('.status-bar.contribute'), new_project_contribution_url(@project), class: 'button small'

  .row.page-main-content
    section.large-9.columns.main
      = render 'projects/draft_warning' if @project.draft?
      = render 'projects/rejected_warning' if @project.rejected?

      nav.tabs[data-target-container=".project-page section.content"]
        = tab_link_to t('.tabs.about'), project_path(@project)

        - if policy(@project).update? || @project.updates.size > 0
          = tab_link_to project_updates_path(@project) do
            = t('.tabs.updates')
            span.count=" #{@project.updates.size}"

        - if @project.total_contributions > 0
          = tab_link_to project_contributions_path(@project) do
            = t('.tabs.contributions')
            span.count=" #{@project.total_contributions}"

        = tab_link_to comments_project_path(@project) do
          = t('.tabs.comments')
          span.commentsCount.count style="display: none;"
            span#countNumber

        = tab_link_to t('.tabs.faqs'), project_faqs_path(@project) if @project.project_faqs.any? || policy(@project).update?
        = tab_link_to t('.tabs.budget'), budget_project_path(@project) if @project.budget.present?
        = tab_link_to t('.tabs.terms'), project_terms_path(@project) if @project.terms.present? || @project.project_documents.any? || policy(@project).update?
        - if policy(@project).update?
          = tab_link_to t('.tabs.reports'), reports_project_path(@project), 'private'

      section.content
        - if content_for? :page_content
          = yield :page_content
        - else
          = render template: 'projects/about', locals: { partial: true }

      section.author
        .row
          - if @project.user.organization?
            .large-5.columns
              = link_to @project.user.display_image_html(width: 300, height: 150, class: 'large'), @project.user
          - else
            .large-3.columns
              = link_to @project.user.display_image_html(width: 150, height: 150, class: 'large'), @project.user

          .columns[class="large-#{ @project.user.organization? ? 7 : 9}"]
            h4 = t('.author.about', name: link_to(@project.user.display_name, @project.user)).html_safe
            p = @project.user.bio

            .social
              ul
                - if @project.user.facebook_url.present?
                  li = link_to @project.user.facebook_url, target: :blank, class: 'facebook' do
                   i.icon-et-facebook-circled
                - if @project.user.twitter_url.present?
                  li = link_to @project.user.twitter_url, target: :blank, class: 'twitter' do
                   i.icon-et-twitter-circled
                - if @project.user.other_url.present?
                  li = link_to @project.user.other_url, target: :blank, class: 'other' do
                   i.icon-et-globe

            - if current_user.present?
              = link_to t('.ask_a_question'), new_user_question_path(@project.user, project_id: @project.id), data: { 'reveal-id' => 'ask-a-question', 'reveal-ajax' => true }, class: 'button ask-a-question-button'
            - else
              = link_to t('.ask_a_question'), new_user_session_path(redirect_to: project_path(@project, anchor: 'open-new-user-question-modal')), class: 'button ask-a-question-button'
            - content_for :modals do
              #ask-a-question.reveal-modal.small.fixed

    aside.large-3.columns.sidebar
      .call-to-action
        - if @project.online?
          noscript
            .alert-box
              strong
                | We're sorry, but you won't be able to contribute without JavaScript enabled.
                br
                br
                | Do you need some #{mail_to t('site.email.contact'), 'help'}?
          = link_to t('.contribute'), new_project_contribution_url(@project), class: "button with-icon contribute"
        - else
          .alert-box.secondary.status-description
            p = t(".display_status.#{@project.campaign_type}.#{@project.display_status}", goal: @project.display_goal, date: (l(@project.display_expires_at.to_date, format: :long) rescue nil))

        = link_to t('.edit'), edit_project_path(@project), class: 'button edit' if policy(@project).update?

      - if @project.last_channel
        section.channel
          = link_to root_url(subdomain: @project.last_channel.permalink) do
            .row
              .large-12.columns.large-centered
                h5 = t('.in_partnership_with')
                = image_tag @project.last_channel.image.large.url

      - if @project.total_contributions > 0
        section.custom.neighbors-behind-this
          .title = t('.neighbors_behind_this')
          .list
            - for contribution in @project.contributions.available_to_display.order("RANDOM()").limit(15)
              - if contribution.anonymous
                = link_to image_tag('anonymous-user.png'), '#', title: t('.anonymous_contribution'), class: 'has-tip', data: { tooltip: '' }
              - else
                = link_to image_tag(contribution.user.display_image), user_path(contribution.user), title: contribution.user.display_name, class: 'has-tip', data: { tooltip: '' }
          .more
            = link_to pluralize(@project.total_contributions, t('words.neighbor_singular'), t('words.neighbor_plural')), project_contributions_path(@project)

      section.rewards[data-rewards-path=project_rewards_path(@project) data-can-update="#{policy(@project).update?}"]